version: "4.12"


services:

  fastapi:
    build: .
    command: [
      "uvicorn",
      "main:app",
      "--host=0.0.0.0",
      "--port=8000",
      "--ssl-keyfile=./cert/localhost-key.pem",
      "--ssl-certfile=./cert/localhost-cert.pem"
    ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"



  redis:
    container_name: redis
    image: redis:7.0.5
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build: .
    command: [
      "celery",
      "-A",
      "apps.celery_worker.celery",
      "worker",
      "-l",
      "info"
    ]
    volumes:
      - ./apps:/app/apps
    depends_on:
      - fastapi
      - redis


  flower:
    container_name: flower
    build: .
    command: [
      "celery",
      "-A",
      "apps.celery_worker.celery",
      "flower",
      "--port=5555"
    ]
    ports:
      - "5556:5555"
    depends_on:
      - fastapi
      - redis
      - celery_worker