server:
  server_host: 127.0.0.1
  server_port: 8000

database_master: ...:...@...:.../master?charset=utf8mb4



email_server:
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_user: aladaris88@gmail.com
  smtp_password: vbqpehyijqiyojal
  service_url: https://localhost:8000/



celery:
  celery_broker_url: redis://redis:6379/0
  celery_backend_result: redis://redis:6379/0


security:
  eschool_secret: "...."
  my_secret_key: ....
  algorithm: HS256
  access_token_expire: 60


kyiv:
  kyiv_client_id: uat-openid-iks-osvita
  kyiv_client_secret: ....
  kyiv_metadata_url: https://auth-stage.kyivcity.gov.ua/.well-known/openid-configuration
  redirect_url: https://localhost:8000/oauth/kyiv/
  journal_eschool_test: https://test.eschool-ua.com/
  diary_eschool_test: https://diary.eschool-ua.com/